name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "email"
database_id = "d0f6a228-37ce-4a0a-a016-899b1a511038"

[[kv_namespaces]]
binding = "kv"
id = "2fc4339a3d4c45eb8f31e4e1bc98b06d"

[[r2_buckets]]
binding = "r2"
bucket_name = "email"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 * * * *"]

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
